version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/openwrt-configurator
    binary: openwrt-configurator
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
      - zip
    format_overrides:
      - goos: linux
        formats:
          - tar.gz
      - goos: darwin
        formats:
          - tar.gz
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*
      - TESTING.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: drummonds
    name: openwrt-configurator
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## OpenWRT Configurator {{ .Tag }}

    ### Installation

    **Linux/macOS:**
    ```bash
    curl -sfL https://raw.githubusercontent.com/drummonds/openwrt-configurator/main/install.sh | sh
    ```

    **Manual installation:**
    Download the appropriate binary for your platform below and extract it to your PATH.

  footer: |
    ### Full Changelog

    See all changes at: https://github.com/drummonds/openwrt-configurator/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap (optional - requires separate tap repository)
# brews:
#   - repository:
#       owner: drummonds
#       name: homebrew-tap
#     homepage: https://github.com/drummonds/openwrt-configurator
#     description: OpenWrt Configuration Tool
#     license: MIT
#     install: |
#       bin.install "openwrt-configurator"
